[package]
name = "opengl-island"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
rand = "0.8.5"
gl = "0.14.0"
winit = "0.30.5"
glutin = "0.32.1"
glutin-winit = "0.5.0"
image = "0.25.5"